[olricd]
partitionCount = 271
backupCount = 1
backupMode = 0
name = "0.0.0.0:3320"
certFile = "/home/burak/Projects/server.pem"
keyFile = "/home/burak/Projects/server.key"
serializer = "gob"

[logging]
level = "DEBUG"
output = "stderr"

[httpClient]
dialerTimeout       = "5s"
insecureSkipVerify  = true
timeout             = "60s"

[memberlist]
environment = "local"
addr = "0.0.0.0:3322"
enableCompression = false
peers = [
  "localhost:3325"
]
